baseURL = 'https://isakkvam.com'
languageCode = 'en-us'
title = 'Isak Kvam, writer'
paginate = 3
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/static/favicon.ico'
  description = "Isak Kvam is a Minnesota-based writer interested in climate, decarbonization, and wild places."
  author = 'Isak Kvam'

  [params.comments]
    enabled = false
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[[module.mounts]]
source = 'content/blog-images/'
target = 'static/blog-images/'
